services:
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
    networks:
      - covid_network

  stats:
    build:
      context: .
      dockerfile: backend/app/stats/Dockerfile.stats
    depends_on:
      - db
      - nats
    environment:
      NATS_URL: nats://nats:4222
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: covid_database
      DB_USER: postgres
      DB_PASSWORD: password
    networks:
      - covid_network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: covid_database
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - covid_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - covid_network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - db
      - redis
      - nats
    entrypoint: [ "sh", "/app/scripts/entrypoint.sh" ]
    restart: always
    environment:
      NATS_URL: nats://nats:4222
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: covid_database
      DB_USER: postgres
      DB_PASSWORD: password
    networks:
      - covid_network
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    networks:
      - covid_network
    ports:
      - "8080:80"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - covid_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - covid_network
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer

  covid-metrics:
    build:
      context: ./backend/app/covid_metrics_exporter
    container_name: covid-metrics
    ports:
      - "9100:9100"
    volumes:
      - ./backend/app/data:/app/data
    networks:
      - covid_network

networks:
  covid_network:

volumes:
  db_data:
  grafana-storage: