global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'covid_metrics'
    static_configs:
      - targets: ['covid-metrics:9100']

  - job_name: 'fastapi_app'
    static_configs:
      - targets: ['backend:8000']