FROM python:3.11-slim

WORKDIR /app

COPY backend/app/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY .env /app/.env

COPY backend/app /app

CMD ["python", "stats_service.py"]
