FROM python:3.11-slim

WORKDIR /app

COPY backend/app/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY backend/app/database /app/database
COPY backend/app/common /app/common
COPY backend/app/stats /app/stats


COPY .env /app/.env

ENV PYTHONPATH=/app

CMD ["python", "stats/stats_service.py"]
